import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const versionFile = path.join(rootDir, 'VERSION');

const VERSION_REGEX = /^\d{4}\.\d{1,2}\.\d+$/;

async function syncVersion() {
  try {
    const version = (await fs.readFile(versionFile, 'utf8')).trim();
    
    if (!VERSION_REGEX.test(version)) {
      console.error(`Invalid version format: "${version}". Expected YYYY.M.PATCH (e.g., 2026.4.1)`);
      process.exit(1);
    }

    console.log(`Syncing version: ${version}`);

    // 1. Update package.json files
    const packages = [
      path.join(rootDir, 'backend', 'package.json'),
      path.join(rootDir, 'frontend', 'package.json')
    ];

    for (const pkgPath of packages) {
      try {
        const pkg = JSON.parse(await fs.readFile(pkgPath, 'utf8'));
        if (pkg.version !== version) {
          pkg.version = version;
          await fs.writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
          console.log(`Updated ${path.relative(rootDir, pkgPath)} to ${version}`);
        }
      } catch (err) {
        console.error(`Error updating ${pkgPath}:`, err.message);
      }
    }

    // 2. Update frontend/src/version.ts
    const frontendVersionFile = path.join(rootDir, 'frontend', 'src', 'version.ts');
    try {
      const content = `// Generated by sync-version.mjs - do not edit manually\nexport const APP_VERSION = '${version}';\n`;
      await fs.writeFile(frontendVersionFile, content);
      console.log(`Updated ${path.relative(rootDir, frontendVersionFile)} to ${version}`);
    } catch (err) {
      console.error(`Error updating ${frontendVersionFile}:`, err.message);
    }

    // 3. Update .env and .env.example
    const envFiles = [
      path.join(rootDir, '.env'),
      path.join(rootDir, '.env.example')
    ];

    for (const envPath of envFiles) {
      try {
        await fs.access(envPath);
        let envContent = await fs.readFile(envPath, 'utf8');
        if (envContent.includes('NEXREV_VERSION=')) {
          envContent = envContent.replace(/NEXREV_VERSION=.*/, `NEXREV_VERSION=${version}`);
        } else {
          envContent += `\n# Application Version\nNEXREV_VERSION=${version}\n`;
        }
        await fs.writeFile(envPath, envContent);
        console.log(`Updated ${path.relative(rootDir, envPath)} to NEXREV_VERSION=${version}`);
      } catch {
        // Skip if file doesn't exist
      }
    }
  } catch (err) {
    console.error(`Error reading version file:`, err.message);
    process.exit(1);
  }
}

syncVersion();
